import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {settingsCaptureFetch, selectedSettings, dsgRouteFetch} from '../harness/inference-settings.mjs';
const records = [], calls = [];
const response = new Response('ok', {headers:{'x-ds4-node':'fixture-node'}});
const stub = (input, init) => { calls.push({input,init}); return Promise.resolve(response); };
const body = '{ "messages": [{"content":"PRIVATE"}], "temperature":0,"chat_template_kwargs":{"enable_thinking":false,"preserve_thinking":true,"reasoning_effort":"xhigh","PRIVATE_KEY":"SECRET"}, "max_tokens":262144 }';
const init = {method:'POST',body,headers:{Authorization:'Bearer PRIVATE_TOKEN'}};
const captured = settingsCaptureFetch(stub,r=>records.push(r));
const output = captured('http://fixture.invalid/v1/chat/completions',init);
assert.equal(calls.length,1,'transport starts before recording');
assert.equal(records.length,0);
assert.equal(await output,response);
await new Promise(setImmediate);
assert.equal(calls[0].init,init,'capture forwards the exact init object');
assert.equal(calls[0].init.body,body,'request bytes are unchanged');
assert.deepEqual(records[0].values,{temperature:0,max_tokens:262144,chat_template_kwargs:{enable_thinking:false,preserve_thinking:true,reasoning_effort:'xhigh'}});
assert(!JSON.stringify(records).includes('PRIVATE'));
await settingsCaptureFetch(stub,()=>{throw Error('broken recorder');})('http://fixture.invalid',init);
await new Promise(setImmediate);
const routeRecords=[];
await dsgRouteFetch(stub,'configured-route',r=>routeRecords.push(r))('http://fixture.invalid',init);
assert.equal(calls.at(-1).init.body,body);
assert.equal(calls.at(-1).init.headers.get('authorization'),'Bearer PRIVATE_TOKEN');
assert.equal(calls.at(-1).init.headers.get('x-dsg-model'),'configured-route');
assert.deepEqual(routeRecords,[{requested_route:'configured-route',observed_node:'fixture-node'}]);
const oversized={method:'POST',body:' '.repeat(8*1024*1024+1)};
await captured('http://fixture.invalid',oversized);
await new Promise(setImmediate);
assert.equal(calls.at(-1).init,oversized,'recording limits must never truncate inference');
assert(records.at(-1).capture_error);
const fixture={messages:[{content:'x'.repeat(32000)}],temperature:0.7,top_k:20};
const serialized=JSON.stringify(fixture),start=performance.now();
for(let i=0;i<100;i++) selectedSettings(JSON.parse(serialized));
console.log(JSON.stringify({checks:'passed',settings_copy_100_requests_ms:+(performance.now()-start).toFixed(3)}));
