'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const store={get(k,d){try{return JSON.parse(localStorage.getItem('hourglass.v2.'+k))??d}catch{return d}},set(k,v){try{localStorage.setItem('hourglass.v2.'+k,JSON.stringify(v))}catch{}}};
let S=null,selected=new Set(store.get('selected',[])),page='bench',limit=20,taskSignature='',modelSignature='',dirty=false,refreshing=false,logId=null,activeDetails=null;
let checked={},toastTimer,liveRunId=null;
let currentQuestionKey='',currentQuestionRequest=0;
const sectionNames={games:'Games',charts:'Charts',math:'Math & logic',code:'Code'};
const sectionKey=s=>s==='chart'?'charts':s==='math_logic'?'math':s;
const sectionName=s=>sectionNames[sectionKey(s)]||s||'Other';
const seconds=s=>s<1?`${(s||0).toFixed(2)}s`:s<60?`${s.toFixed(1)}s`:`${Math.floor(s/60)}m ${Math.round(s%60)}s`;
const median=a=>{a=[...a].sort((a,b)=>a-b);return a.length?(a[Math.floor(a.length/2)]+a[Math.ceil(a.length/2)-1])/2:0};
const version=r=>r.benchmark_version||'unversioned';
const resultLabel=r=>r.status==='not_attempted'?'Not attempted · awaiting retry':['five_wrong_in_row','wrong_streak_limit'].includes(r.score_reason)?'Not attempted · 0':r.score_reason==='unsupported_vision'?'Vision unsupported · 0':r.status==='error'?'Execution error':r.solved?'Correct':'Incorrect';
const outcome=r=>r.status==='not_attempted'?'not_attempted':r.status==='error'?'error':r.solved?'correct':'incorrect';
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5000)}
async function api(url,body){const r=await fetch(url,body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||`Request failed (${r.status})`);return data}

function setPage(p){if(!['bench','results','settings','current'].includes(p))p='bench';page=p;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('hidden',el.id!=='page-'+p));document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.page===p));if(location.hash!=='#'+p)history.replaceState(null,'','#'+p);if(p==='results'&&S)renderResults();if(p==='current'&&S)renderCurrentQuestion()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setPage(b.dataset.page));window.addEventListener('hashchange',()=>setPage(location.hash.slice(1)));$('backToBench').onclick=()=>setPage('bench');
function updateSelection(){store.set('selectionInitialized',true);store.set('selected',[...selected]);renderLibrary();renderBuilder()}
function filteredTasks(){if(!S)return[];const q=$('search').value.toLowerCase(),section=$('sectionFilter').value,tier=$('tierFilter').value;return S.tasks.filter(t=>(!section||sectionKey(t.section)===section)&&(!tier||(tier==='untiered'?(t.order_tier??t.tier)==null:String(t.order_tier??t.tier)===tier))&&(!q||`${t.id} ${t.title} ${t.family}`.toLowerCase().includes(q)))}
function renderLibrary(){const rows=filteredTasks(),shown=rows.slice(0,limit);$('libraryCaption').textContent=`${rows.length} question${rows.length===1?'':'s'} · ${new Set(rows.map(t=>t.family)).size} ${new Set(rows.map(t=>t.family)).size===1?'family':'families'}`;$('taskRows').innerHTML=shown.map(t=>`<tr class="${selected.has(t.id)?'selected-row':''}"><td class="checkcol"><input type="checkbox" data-task="${esc(t.id)}" aria-label="Select ${esc(t.id)} ${esc(t.title)}" ${selected.has(t.id)?'checked':''} ${t.issues.length?'disabled':''}></td><td><span class="questiontitle">${esc(t.title)}</span><span class="questionmeta"><code>${esc(t.id)}</code> ${esc(t.family)}${questionReviewFlag(t.id)}${t.issues.length?' · Needs attention':''}</span></td><td><span class="tier t${Number(t.order_tier??t.tier)}" title="${esc(t.tier_estimated?`Estimated from ${t.level.replaceAll('_',' ')}`:'Authored difficulty tier')}">${(t.order_tier??t.tier)==null?'Untiered':`${t.tier_estimated?'~':''}T${Number(t.order_tier??t.tier)}`}</span></td><td><span class="format">${t.vision?'Image + tools':t.kind==='fix'?'Code repair':t.mode==='numeric'?'Numeric':`${t.options} options`}</span></td><td><button class="iconbutton" data-preview="${esc(t.id)}" aria-label="Preview ${esc(t.id)}" title="Preview question">↗</button></td></tr>`).join('');$('shownCount').textContent=`Showing ${shown.length} of ${rows.length}`;$('moreTasks').classList.toggle('hidden',shown.length>=rows.length);$('noTasks').classList.toggle('hidden',rows.length>0);$('selectionCount').textContent=`${selected.size} selected`;$('selectedBadge').textContent=selected.size;$('clearSelection').disabled=!selected.size;$('selectAll').disabled=!S.tasks.some(t=>!t.issues.length&&!selected.has(t.id));$('selectMatching').disabled=!rows.some(t=>!t.issues.length&&!selected.has(t.id));$('selectMatching').classList.toggle('hidden',!$('search').value&&!$('sectionFilter').value&&!$('tierFilter').value);$('taskRows').querySelectorAll('[data-task]').forEach(el=>el.onchange=()=>{el.checked?selected.add(el.dataset.task):selected.delete(el.dataset.task);updateSelection()});$('taskRows').querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(b.dataset.preview))}
for(const id of ['search','sectionFilter','tierFilter'])$(id).addEventListener(id==='search'?'input':'change',()=>{limit=20;renderLibrary()});$('moreTasks').onclick=()=>{limit+=20;renderLibrary()};$('clearSelection').onclick=()=>{selected.clear();updateSelection()};function selectQuestions(tasks){tasks.filter(t=>!t.issues.length).forEach(t=>selected.add(t.id));updateSelection()}
$('selectAll').onclick=()=>{if(S)selectQuestions(S.tasks)};$('selectMatching').onclick=()=>selectQuestions(filteredTasks());
function starter(){if(!S)return;const task=S.tasks.find(t=>t.id==='G002')||S.tasks.find(t=>!t.vision&&!t.issues.length);if(!task){toast('No ready starter question is installed.');return}selected=new Set([task.id]);$('search').value=task.id;$('sectionFilter').value='';$('tierFilter').value='';$('repeat').value=1;$('taskDefaults').checked=false;setPage('bench');updateSelection();window.scrollTo({top:0,behavior:'smooth'})}
$('starterBtn').onclick=starter;$('resultStarter').onclick=starter;
function modelConfig(){return S?.model_configs.find(m=>m.name===$('model').value)}
function selectedTasks(){return S?S.tasks.filter(t=>selected.has(t.id)):[]}
function repeatValue(){return $('taskDefaults').checked?null:Number($('repeat').value)}
function renderBuilder(){const m=modelConfig(),tasks=selectedTasks();$('modelInfo').innerHTML=m?`<div>${esc(m.model)}</div><div>${esc(m.base_url)}</div><div class="modelchips"><span>max_tokens ${esc(m.extra?.max_tokens??m.max_tokens??1024)}</span><span>temperature: server default</span></div>`:'No model is configured. Add one in Model settings.';$('repeat').disabled=$('taskDefaults').checked;const repeat=repeatValue(),attempts=tasks.reduce((n,t)=>n+(repeat??t.repeat),0),validRepeat=repeat===null||Number.isInteger(repeat)&&repeat>0;$('selectionSummary').innerHTML=tasks.length?`<strong>${tasks.length} question${tasks.length===1?'':'s'} · ${validRepeat?attempts:'—'} attempt${attempts===1?'':'s'}</strong><small>${esc(tasks.slice(0,4).map(t=>t.id).join(', '))}${tasks.length>4?` + ${tasks.length-4} more`:''}</small>`:'Select a question to build your run.';$('reviewRun').disabled=!tasks.length||!m||!validRepeat||tasks.some(t=>t.issues.length);$('visionNote').textContent=m?.supports_vision===false?'This model has no vision support. Image questions count as zero and are not sent to the model.':'Vision support is detected from the endpoint response. Unsupported image questions count as zero automatically.';$('visionNote').classList.toggle('hidden',!tasks.some(t=>t.vision));$('checkModel').disabled=!m;renderEndpoint()}
function renderEndpoint(){const m=modelConfig(),c=m&&checked[m.name];$('endpointDetails').classList.add('hidden');$('endpointStatus').textContent=c?(c.reachable?(c.listed?'Endpoint reachable':'Model ID not listed'):'Endpoint unavailable'):'Connection not checked';$('endpointStatus').style.color=c?(c.reachable&&c.listed?'var(--green)':'var(--amber)'):'';if(c){$('endpointDetails').classList.remove('hidden');$('endpointDetails').classList.toggle('error',!c.reachable);$('endpointDetails').textContent=!c.reachable?`Could not reach this server. ${c.message}`:!c.listed?`Server responds, but “${m.model}” is not listed. Available: ${c.available.join(', ')||'(none)'}. Check the exact ID in Model settings.`:c.message}}
$('model').onchange=()=>{store.set('model',$('model').value);renderBuilder()};$('repeat').oninput=renderBuilder;$('taskDefaults').onchange=renderBuilder;
$('checkModel').onclick=async()=>{const name=$('model').value,b=$('checkModel');b.disabled=true;b.textContent='Checking…';try{checked[name]=await api('/api/check-model',{model:name});renderEndpoint()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Check connection'}};
function dialog(title,html,actions=[]){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;$('dialogActions').innerHTML='';for(const a of actions){const b=document.createElement('button');b.className='button '+(a.primary?'primary':'secondary');b.textContent=a.label;b.onclick=()=>a.click(b);$('dialogActions').append(b)}if(!$('dialog').open)$('dialog').showModal()}
$('closeDialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('dialog').close()}});
async function preview(id){try{const t=await api('/api/task?id='+encodeURIComponent(id));dialog(`${id} · ${t.title}`,`<p class="help">Preview shows the question and public workspace files, not the answer key.</p><pre class="previewtext">${esc(t.prompt)}</pre><details><summary>${t.options.length} options</summary><pre class="previewtext">${esc(t.options.map(o=>typeof o==='string'?o:`${o.id} — ${o.text}`).join('\n'))}</pre></details><p class="help">Workspace: ${esc(t.files.join(', ')||'Question and attached assets')}</p>`,[{label:selected.has(id)?'Remove from run':'Add to run',primary:true,click:()=>{selected.has(id)?selected.delete(id):selected.add(id);updateSelection();$('dialog').close()}}])}catch(e){toast(e.message)}}
$('reviewRun').onclick=()=>{const m=modelConfig(),tasks=selectedTasks(),repeat=repeatValue(),attempts=tasks.reduce((n,t)=>n+(repeat??t.repeat),0),request={model:m.name,tasks:tasks.map(t=>t.id),repeat};dialog('Review your run',`<dl class="reviewgrid"><dt>Model</dt><dd><strong>${esc(m.name)}</strong><br>${esc(m.model)}</dd><dt>Endpoint</dt><dd>${esc(m.base_url)}</dd><dt>Attempts</dt><dd>${attempts} across ${tasks.length} question${tasks.length===1?'':'s'}</dd><dt>Repeats</dt><dd>${repeat??'Each question’s saved default'}</dd><dt>Output limit</dt><dd>${esc(m.extra?.max_tokens??m.max_tokens??1024)} tokens, from saved settings</dd><dt>Execution</dt><dd>Ascending difficulty tier, alternating sections. Stop after ${S.execution_policy?.stop_after_wrong??20} consecutive incorrect questions; remaining questions score zero. Automatic stop and completion chime after 60 active minutes.</dd></dl><ul class="reviewlist">${tasks.map(t=>`<li><strong>${esc(t.id)}</strong> · ${esc(t.title)}</li>`).join('')}</ul><p class="help">${S.jobs.running.length||S.jobs.pending.length?'This run will wait for existing work to finish.':'Starting sends the selected questions to your configured model.'}</p>`,[{label:'Back',click:()=>$('dialog').close()},{label:S.jobs.running.length?'Add to queue':'Start run',primary:true,click:async b=>{b.disabled=true;b.textContent='Starting…';try{const r=await api('/api/run',request);logId=r.job;liveRunId=r.job;$('dialog').close();toast('Run added. Follow its progress below.');await refresh();$('jobs').scrollIntoView({behavior:'smooth',block:'center'})}catch(e){toast(e.message);b.disabled=false;b.textContent='Start run'}}}])};
function renderJobs(){renderLiveRun();const j=S.jobs,all=[...j.running,...j.pending,...j.done.slice().reverse().slice(0,8)];$('activityCaption').textContent=j.running.length?`Running ${j.running[0].current_task||'first question'} · ${j.pending.length} waiting`:j.pending.length?`${j.pending.length} waiting to start`:'Runs execute one at a time.';$('activityBadge').textContent=j.running.length?'Running':j.pending.length?'Queued':'Idle';$('activityBadge').className='statusbadge '+(j.running.length?'active':'');$('jobs').innerHTML=all.length?all.map(r=>`<div class="jobrow"><span class="statusbadge ${r.state==='error'?'bad':r.state==='completed'?'good':r.state==='running'?'active':''}">${esc(r.state)}</span><div class="joblabel"><strong>${esc(r.label)}</strong><small>${r.state==='running'?`${r.completed_tasks||0}/${r.total_tasks} questions complete · ${Math.floor(Date.now()/1000-r.started)}s elapsed`:r.error?esc(r.error):r.state==='completed'?(r.stopped_after?`Stopped after ${esc(r.stopped_after)}: ${r.stop_after_wrong??5} incorrect questions in a row. Remaining questions scored zero.`:`${r.total_tasks} questions completed · inspect Results for scores`):r.state==='cancelled'?'Removed before starting':'Waiting for its turn'}</small></div>${r.state==='running'?`<progress value="${r.completed_tasks||0}" max="${r.total_tasks}"></progress>`:''}${!['running','pending'].includes(r.state)?`<button class="textbutton" data-clear-run="${esc(r.id)}">Clear run</button>`:''}${r.state==='running'?`<button class="textbutton" data-stop-run="${esc(r.id)}" ${r.stop_requested?'disabled':''}>${r.stop_requested?'Stopping…':'Stop run'}</button>`:''}${r.resume?.allowed?`<button class="textbutton" data-resume="${esc(r.id)}">Resume run</button>`:''}${r.state==='pending'?`<button class="textbutton" data-cancel="${esc(r.id)}">Remove</button>`:r.state!=='cancelled'?`<button class="textbutton" data-log="${esc(r.id)}">View log</button>`:''}</div>`).join(''):'<div class="activityempty">No runs yet. Choose a question above to get started.</div>';$('jobs').querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>{logId=b.dataset.log;loadLog()});$('jobs').querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{try{await api('/api/cancel',{job:b.dataset.cancel});toast('Waiting run removed.');refresh()}catch(e){toast(e.message)}});$('jobs').querySelectorAll('[data-resume]').forEach(b=>b.onclick=()=>reviewResume(b.dataset.resume));$('jobs').querySelectorAll('[data-clear-run]').forEach(b=>b.onclick=()=>reviewClearRun(b.dataset.clearRun));$('jobs').querySelectorAll('[data-stop-run]').forEach(b=>b.onclick=()=>stopRun(b.dataset.stopRun));if(logId)loadLog()}
async function loadLog(){const id=logId;if(!id)return;try{const r=await fetch('/api/log?job='+encodeURIComponent(id));if(!r.ok)throw Error('Log unavailable');const t=await r.text();if(id!==logId)return;$('logWrap').classList.remove('hidden');const atBottom=$('jobLog').scrollTop+$('jobLog').clientHeight>=$('jobLog').scrollHeight-40;$('jobLog').textContent=t;if(atBottom)$('jobLog').scrollTop=$('jobLog').scrollHeight}catch(e){$('jobLog').textContent=e.message}}
function filteredResults(){const q=$('resultSearch').value.toLowerCase(),sec=$('resultSection').value,status=$('resultStatus').value;return S.results.filter(r=>(!q||`${r.task} ${r.model}`.toLowerCase().includes(q))&&(!sec||sectionKey(r.section||S.tasks.find(t=>t.id===r.task)?.section)===sec)&&(!status||outcome(r)===status))}
function renderResults(){renderHourScores();loadCalibration();const any=S.results.length>0;$('resultEmpty').classList.toggle('hidden',any);$('resultContent').classList.toggle('hidden',!any);if(!any)return;const rows=filteredResults(),scored=rows.filter(r=>outcome(r)!=='error'),correct=scored.filter(r=>r.solved).length;$('statRuns').textContent=scored.length;$('statAccuracy').textContent=scored.length?`${(100*correct/scored.length).toFixed(1)}%`:'—';$('statTime').textContent=scored.length?seconds(median(scored.map(r=>r.duration_s||0))):'—';$('statErrors').textContent=rows.length-scored.length;const groups=new Map();for(const r of scored){const k=r.model+' @ '+(r.node||'?')+' · Hourglass Bench '+version(r);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}const stats=[...groups].map(([name,rs])=>({name,n:rs.length,acc:rs.filter(r=>r.solved).length/rs.length,time:median(rs.map(r=>r.duration_s||0))}));$('modelComparison').innerHTML=stats.length?stats.map(s=>`<tr><td>${esc(s.name)}</td><td>${s.n}</td><td>${(100*s.acc).toFixed(1)}%</td><td>${seconds(s.time)}</td></tr>`).join(''):'<tr><td colspan="4">No scored attempts in this filter.</td></tr>';drawScatter(stats);$('resultRows').innerHTML=rows.slice().reverse().map((r,i)=>`<tr class="clickrow" data-result="${i}" tabindex="0" role="button" aria-label="Open ${esc(r.task)} result"><td><strong>${esc(r.task)}</strong><span class="questionmeta">Tier ${esc(r.tier)} · v${esc(version(r))}</span></td><td>${esc(r.model)}</td><td><span class="statusbadge ${outcome(r)==='correct'?'good':outcome(r)==='error'?'bad':''}">${esc(resultLabel(r))}</span></td><td>${seconds(r.duration_s||0)}</td><td>${r.tool_calls??'—'}</td><td>${esc(new Date(r.ts).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}))}</td></tr>`).join('');const reversed=rows.slice().reverse();$('resultRows').querySelectorAll('[data-result]').forEach(el=>{el.onclick=()=>resultDetail(reversed[+el.dataset.result]);el.onkeydown=e=>{if(e.key==='Enter')el.click()}})}
function drawScatter(stats){const W=480,H=230,max=Math.max(1,...stats.map(s=>s.time))*1.15,x=t=>45+t/max*410,y=a=>190-a*158;let html='';for(let i=0;i<=4;i++){let yy=y(i/4);html+=`<line x1="45" x2="455" y1="${yy}" y2="${yy}" stroke="#e4e8de"/><text x="32" y="${yy+3}" text-anchor="end" fill="#788273" font-size="9">${i*25}%</text>`}html+=`<text x="45" y="216" font-size="9" fill="#788273">0s</text><text x="455" y="216" text-anchor="end" font-size="9" fill="#788273">${seconds(max)}</text>`;for(const s of stats)html+=`<circle cx="${x(s.time)}" cy="${y(s.acc)}" r="7" fill="#28674f" opacity=".85"><title>${esc(s.name)}: ${(s.acc*100).toFixed(1)}%, ${seconds(s.time)}, ${s.n} attempts</title></circle>`;$('scatter').innerHTML=html}
for(const id of ['resultSearch','resultSection','resultStatus'])$(id).addEventListener(id==='resultSearch'?'input':'change',()=>S&&renderResults());
function resultDetail(r){activeDetails=r;const n=r.opt_n||S.tasks.find(t=>t.id===r.task)?.options;dialog(`${r.task} · ${resultLabel(r)}`,`<dl class="reviewgrid"><dt>Model</dt><dd>${esc(r.model)}</dd><dt>Hourglass Bench version</dt><dd>${esc(version(r))}</dd><dt>Harness</dt><dd>${esc(r.harness==='pi'?`Frozen Pi ${r.pi_version}`:'Legacy harness')}</dd><dt>Temperature</dt><dd>${esc(r.temperature??'Not reported')} · ${esc(r.temperature_source??'Not recorded in this historical result')}</dd>${thinkingDetails(r)}<dt>Submitted answer</dt><dd><code>${esc(JSON.stringify(r.parsed_answer??{}))}</code></dd><dt>Elapsed time</dt><dd>${seconds(r.duration_s||0)}</dd><dt>Tokens</dt><dd>${r.prompt_tokens??0} input · ${r.completion_tokens??0} output</dd><dt>Tool calls</dt><dd>${r.tool_calls??0}</dd><dt>Evaluation</dt><dd>${r.mode==='numeric'?'Numeric tolerance':n?`Exact answer · ${n} options`:'Hidden verifier'}</dd></dl>${r.error?`<div class="notice error">${esc(r.error)}</div>`:''}<details><summary>Requested and reported settings</summary><h3>Requested by Hourglass Bench</h3><pre class="previewtext">${esc(r.requested_settings?JSON.stringify(r.requested_settings,null,2):'Not captured in this historical attempt')}</pre><h3>Server-reported</h3><pre class="previewtext">${esc(r.server_settings?JSON.stringify(r.server_settings,null,2):'Not reported')}</pre><h3>User-reported run history</h3>${settingsHistory(r.user_settings||[])}<p class="help">These are dated observations, not verified effective values for this attempt.</p></details><div class="detailtabs"><button data-artifact="metrics.json">Metrics</button><button data-artifact="trace.json">Tool trace</button><button data-artifact="patch.diff">Code changes</button></div><pre id="artifact" class="previewtext">${esc(r.verified_output||'Choose an artifact above.')}</pre>`,[{label:'Close',click:()=>$('dialog').close()}]);document.querySelectorAll('[data-artifact]').forEach(b=>b.onclick=async()=>{const dir=r.artifact_dir||`results/${r.task}/${r.model}/run-${r.run}`;try{const res=await fetch('/api/file?path='+encodeURIComponent(dir+'/'+b.dataset.artifact));if(!res.ok)throw Error('Artifact not found');const text=await res.text();if(activeDetails===r)$('artifact').textContent=text||'(No changes)'}catch(e){$('artifact').textContent=e.message}})}
$('modelJson').oninput=()=>{dirty=true;$('dirtyBadge').classList.remove('hidden');$('saveStatus').textContent=''};$('discardModels').onclick=()=>{dirty=false;$('modelJson').value=S.models_json;$('dirtyBadge').classList.add('hidden');$('saveStatus').textContent='Edits discarded.'};$('saveModels').onclick=async()=>{const b=$('saveModels');b.disabled=true;$('saveStatus').textContent='Saving…';try{const r=await api('/api/models',{text:$('modelJson').value});dirty=false;checked={};$('dirtyBadge').classList.add('hidden');$('saveStatus').textContent='Saved. Previous settings backed up.';toast(`Saved; backup in ${r.backup}`);await refresh()}catch(e){$('saveStatus').textContent=e.message;toast(e.message)}finally{b.disabled=false}};$('probe').onclick=async()=>{const b=$('probe');b.disabled=true;b.textContent='Reading machine record…';try{const r=await api('/api/probe',{});if(!r.ok)throw Error(r.out);await refresh();toast('Machine record refreshed.')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Refresh provenance'}};
async function refresh(){if(refreshing)return;refreshing=true;try{const next=await api('/api/state');S=next;$('connectionError').classList.add('hidden');$('bankCount').textContent=S.tasks.length;$('resultCount').textContent=S.results.length;$('firstGuide').classList.toggle('hidden',S.results.length>0);$('page-bench').querySelector('h1').textContent=S.results.length?'Build your next run.':'Build your first run.';const ts=JSON.stringify(S.tasks);if(ts!==taskSignature){taskSignature=ts;if(!store.get('selectionInitialized',false)){selected=new Set(S.tasks.filter(t=>!t.issues.length).map(t=>t.id));store.set('selected',[...selected]);store.set('selectionInitialized',true)}else{selected=new Set([...selected].filter(id=>S.tasks.some(t=>t.id===id)))}for(const id of ['sectionFilter','resultSection']){const el=$(id),v=el.value;el.innerHTML='<option value="">All sections</option>'+[...new Set(S.tasks.map(t=>sectionKey(t.section)))].sort().map(s=>`<option value="${esc(s)}">${esc(sectionName(s))}</option>`).join('');el.value=v}renderLibrary()}const ms=JSON.stringify(S.model_configs);if(ms!==modelSignature){modelSignature=ms;const prev=$('model').value||store.get('model','');$('model').innerHTML=S.model_configs.map(m=>`<option value="${esc(m.name)}">${esc(m.name)}</option>`).join('');if(S.models.includes(prev))$('model').value=prev;checked={}}if(!dirty)$('modelJson').value=S.models_json;renderBuilder();renderJobs();if(page==='results')renderResults();if(page==='current')renderCurrentQuestion();const p=S.provenance;$('provenance').textContent=JSON.stringify({node:p.node,chip:p.chip,ram_gb:p.ram_bytes&&!isNaN(+p.ram_bytes)?Math.round(+p.ram_bytes/2**30):undefined,python:p.python,pi_version:p.pi_version,captured_at:p.captured_at},null,2);$('lastUpdated').textContent='Connected · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});if(S.model_errors.length){$('connectionError').textContent='Model configuration needs attention: '+S.model_errors.join('; ');$('connectionError').classList.remove('hidden')}}catch(e){$('connectionError').textContent='Cannot reach the Hourglass Bench console. Check that its launcher is running. '+e.message;$('connectionError').classList.remove('hidden');$('lastUpdated').textContent='Disconnected'}finally{refreshing=false}}
setPage(location.hash.slice(1)||'bench');refresh();setInterval(refresh,2500);

let calibrationData=null,calibrationLoading=false;
const pct=x=>x===null||x===undefined?'—':`${(x*100).toFixed(1)}%`;
async function loadCalibration(){
  if(calibrationLoading)return;
  if(!S?.calibration_available){$('calibrationStatus').textContent='Calibration is installed. After the active run finishes, restart the Hourglass Bench UI server to enable it. Your model server can stay running.';return}
  calibrationLoading=true;
  try{calibrationData=await api('/api/calibration');renderCalibration()}
  catch(e){$('calibrationStatus').textContent=e.message}
  finally{calibrationLoading=false}
}
$('refreshCalibration').onclick=loadCalibration;
$('calibrationScope').onchange=renderCalibration;
function renderCalibration(){
  if(!calibrationData)return;
  const evs=calibrationData.evaluations,select=$('calibrationScope'),previous=select.value;
  const scopes=[...new Set(evs.map(e=>e.scope))];
  select.innerHTML=scopes.length?scopes.map(id=>{const e=evs.find(e=>e.scope===id);return `<option value="${esc(id)}">v${esc(e.benchmark_version)} · ${e.questions} questions · ${e.expected_attempts} attempts · ${id.slice(0,8)}</option>`}).join(''):'<option value="">No evaluations yet</option>';
  if(scopes.includes(previous))select.value=previous;
  const id=select.value,rows=evs.filter(e=>e.scope===id),scope=calibrationData.scopes[id],fit=scope?.fit;
  $('calibrationStatus').textContent=evs.length?'References are saved separately from model settings. Only complete evaluations with the same version, question content and repeats share a scale.':'Start a run from the benchmark page. Its complete evaluation will appear here.';
  $('calibrationFit').innerHTML=fit?`<div class="notice ${fit.status==='blocked'?'error':''}"><strong>${esc(fit.message)}</strong>${fit.status==='ready'?`<div>Legacy calibrated score = ${fit.intercept.toFixed(3)} + ${fit.slope.toFixed(3)} × accuracy (0–1).</div><div>Reference range: ${pct(fit.accuracy_min)}–${pct(fit.accuracy_max)}. Fit RMSE: ${fit.rmse.toFixed(2)}${fit.leave_one_out_mae!==null?` · Held-out reference MAE: ${fit.leave_one_out_mae.toFixed(2)}`:''}.</div>`:''}${fit.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}<small>Calibration revision ${esc(scope.revision.slice(0,8))}. Scores outside the reference range are withheld.</small></div>`:'<div class="notice">Assign targets to at least two different models to create this scale.</div>';
  $('calibrationRows').innerHTML=rows.length?rows.map(e=>{
    const ref=scope?.references.find(r=>r.evaluation_id===e.id);
    return `<tr><td><strong>${esc(e.model)}</strong><small>${esc(e.node||'Pending')} · ${esc(new Date(e.created*1000).toLocaleString())}</small><small>${esc(e.id.slice(0,8))}</small></td><td>${e.attempts}/${e.expected_attempts}<small>${e.eligible?(e.not_attempted?`${e.not_attempted} not attempted · scored zero`:'Ready'):esc(e.reasons.join(' '))}</small></td><td>${pct(e.breakdown.text.accuracy)} / ${pct(e.breakdown.vision.accuracy)}<small>${e.breakdown.text.questions} text · ${e.breakdown.vision.questions} vision questions</small></td><td>${pct(e.accuracy)}</td><td>${seconds(e.duration_s)}<small>Sum of measured attempt times</small></td><td><strong>${e.calibrated_score===null?'—':e.calibrated_score.toFixed(2)}</strong><small>${esc(e.score_note)}</small></td><td>${ref?`<strong>${ref.target}</strong><br>`:''}<button class="textbutton" data-reference="${esc(e.id)}" ${e.eligible?'':'disabled'}>${ref?'Edit target':'Set target'}</button></td></tr>`
  }).join(''):'<tr><td colspan="7">No evaluations recorded yet.</td></tr>';
  $('calibrationRows').querySelectorAll('[data-reference]').forEach(b=>b.onclick=()=>editReference(b.dataset.reference));
  $('calibrationReferences').innerHTML=scope?.references.length?`<h3>Reference targets</h3><p class="help">With three or more references, the fitted score may differ from an assigned target. One saved reference per model ID prevents repeated runs from gaining extra weight.</p><div class="tablewrap"><table><thead><tr><th>MODEL</th><th>ACCURACY</th><th>TARGET</th><th>FITTED</th><th>TARGET − FITTED</th><th></th></tr></thead><tbody>${scope.references.map(r=>{const residual=fit.residuals?.find(x=>x.model===r.model);return `<tr><td>${esc(r.model)}</td><td>${pct(r.accuracy)}</td><td>${r.target}</td><td>${residual?residual.fitted.toFixed(2):'—'}</td><td>${residual?residual.residual.toFixed(2):'—'}</td><td><button class="textbutton" data-remove-reference="${esc(r.evaluation_id)}">Remove reference</button></td></tr>`}).join('')}</tbody></table></div>`:'';
  $('calibrationReferences').querySelectorAll('[data-remove-reference]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/calibration/remove',{scope:id,evaluation_id:b.dataset.removeReference});await loadCalibration()}catch(e){toast(e.message);b.disabled=false}});
}
function editReference(id){
  const e=calibrationData.evaluations.find(e=>e.id===id),scope=calibrationData.scopes[e.scope],existing=scope?.references.find(r=>r.model_id===e.model_id);
  dialog(`Reference target · ${e.model}`,`<p>Measured accuracy: <strong>${pct(e.accuracy)}</strong> over ${e.questions} questions, Hourglass Bench v${esc(e.benchmark_version)}.</p><label class="fieldlabel" for="referenceTarget">Legacy calibration target</label><input class="repeatinput" id="referenceTarget" type="number" min="0" step="any" placeholder="For example, 1 or 5" value="${existing?.target??''}"><p class="help">${existing?'This replaces this model’s existing reference for the same question set.':'The target defines your reference scale; it does not alter measured results.'} Inconsistent targets are saved for editing but block score calculation.</p><p id="referenceError" class="help" role="alert"></p>`,[{label:'Cancel',click:()=>$('dialog').close()},{label:'Save target',primary:true,click:async b=>{const raw=$('referenceTarget').value,target=Number(raw);if(!raw.trim()||!Number.isFinite(target)||target<0){$('referenceError').textContent='Enter a finite, non-negative target.';return}b.disabled=true;try{await api('/api/calibration/reference',{evaluation_id:id,target});$('dialog').close();await loadCalibration();toast('Reference target saved.')}catch(e){$('referenceError').textContent=e.message;b.disabled=false}}}]);
}
$('copyFullLog').onclick=async()=>{
  const id=logId,b=$('copyFullLog');if(!id){toast('Open a run log first.');return}
  b.disabled=true;b.textContent='Copying…';
  try{
    const r=await fetch('/api/log/full?job='+encodeURIComponent(id));
    if(!r.ok)throw Error(S?.calibration_available?'The full log is not available yet.':'Full-log copying needs the updated UI server. Restart Hourglass Bench after the active run finishes.');
    const text=await r.text();
    await navigator.clipboard.writeText(text);
    toast(`Full log copied (${text.length.toLocaleString()} characters).`);
  }catch(e){toast('Could not copy: '+e.message)}
  finally{b.disabled=false;b.textContent='Copy full log'}
};

function scoreFor(job){if(job.hour_score?.weighted_version)return job.hour_score;const metadata=new Map(S.tasks.map(t=>[t.id,t]));const expected=(job.expected||job.tasks.map(task=>({task}))).map(t=>({...metadata.get(t.task),...t}));return hourScore(job,S.results,expected)}
function hourState(h){return {final:'Final',in_progress:'In progress',partial:'Partial · ended before one hour',not_started:'Not started',unavailable:'Timing unavailable'}[h.state]}
function renderHourScores(){
  const jobs=allJobs();
  $('hourScoreRows').innerHTML=jobs.length?jobs.map(j=>{const h=scoreFor(j),v=n=>n===null?'—':n,w=n=>n==null?'—':Number(n).toFixed(2);return `<tr><td>${esc(j.model)}<span class="questionmeta">${h.total_questions} questions · ${esc(j.id.slice(0,8))}</span></td><td><strong>${w(h.weighted_points)}</strong><span class="questionmeta">${v(h.points)} correct</span></td><td>${w(h.breakdown.text.weighted_points)}</td><td>${w(h.breakdown.vision.weighted_points)}</td><td>${hourState(h)} <button class="textbutton" onclick="window.open('http://127.0.0.1:'+ (Number(location.port)+20) +'/?job=${encodeURIComponent(j.id)}','_blank')">Publish score</button></td></tr>`}).join(''):'<tr><td colspan="5">Start a run to record a one-hour score.</td></tr>';
}
function allJobs(){return [...S.jobs.running,...S.jobs.pending,...S.jobs.done.slice().reverse()]}
function renderLiveRun(){
  const jobs=allJobs();$('liveRun').classList.toggle('hidden',!jobs.length);if(!jobs.length){liveRunId=null;logId=null;$('logWrap').classList.add('hidden');return;}
  const job=jobs.find(j=>j.id===liveRunId)||jobs[0];liveRunId=job.id;
  $('liveRunSelect').innerHTML=jobs.map(j=>`<option value="${esc(j.id)}">${esc(j.model)} · ${j.tasks?.length===1?esc(j.tasks[0]):`${j.total_tasks??j.tasks?.length??0} questions`} · ${esc(j.state)} · ${esc(new Date(j.created*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}))}</option>`).join('');$('liveRunSelect').value=job.id;
  $('liveRunTitle').textContent=job.model+' · '+(job.tasks?.length===1?job.tasks[0]:`${job.total_tasks??job.tasks?.length??0} questions`);
  $('liveSettingsSummary').textContent=job.user_settings?.length?`${job.user_settings.length} user-reported settings record(s) · latest saved ${new Date(job.user_settings.at(-1).recorded_at*1000).toLocaleString()}`:'Sampling settings unknown? Optionally record what your server shows.';
  renderSpeed(job);
  const p=job.progress;
  $('liveStop').classList.toggle('hidden',job.state!=='running');$('liveStop').disabled=!!job.stop_requested;$('liveStop').textContent=job.stop_requested?'Stopping…':'Stop run';$('liveResume').classList.toggle('hidden',!job.resume?.allowed);$('liveClear').classList.toggle('hidden',job.state==='running'||job.state==='pending');
  if(!p){$('liveMetrics').textContent='Live statistics will appear when the updated backend is available.';return}
  const h=scoreFor(job), scoreValue=n=>n===null?'—':Number(n).toFixed(2);
  $('liveSplit').innerHTML=['text','vision'].map(lane=>{const b=p.breakdown?.[lane],hb=h.breakdown[lane];if(!b)return '';return `<section><h3>${lane==='text'?'Text':'Vision'}</h3><strong>${scoreValue(hb.weighted_points)} <small>points in the first hour</small></strong><p>${hb.points} correct · ${hb.completed_questions} completed within the scoring window</p><p>Full run: ${b.points} / ${b.total_questions} points · ${b.finished_questions} questions scored</p></section>`}).join('');
  $('liveMetrics').innerHTML=`<div><span>Hourglass Bench score · 1 hour</span><strong>${scoreValue(h.weighted_points)}</strong><small>${h.points} correct · ${hourState(h)} · ${h.completed_questions} completed within the hour</small></div><div><span>Scoring time remaining</span><strong>${seconds(h.remaining_s)}</strong><small>60 minutes of active time; no extrapolation</small></div><div><span>Full-run accuracy</span><strong>${p.accuracy===null?'—':(p.accuracy*100).toFixed(1)+'%'}</strong><small>${p.correct_attempts} / ${p.scored_attempts} scored attempts, including after the hour</small></div><div><span>Active run time</span><strong>${seconds(p.elapsed_s)}</strong><small>Thinking, tools and retries included; pauses excluded</small></div>`;
  $('liveProgress').max=p.total_questions;$('liveProgress').value=p.finished_questions;
  $('liveProgressText').textContent=`${p.finished_questions} / ${p.total_questions} questions scored · ${p.wrong_streak} / ${p.stop_after_wrong} consecutive wrong${p.not_attempted?' · '+p.not_attempted+' unattempted zeros':''}${p.errors?' · '+p.errors+' execution error'+(p.errors===1?'':'s')+' recorded':''}${job.state==='running'?' · Working on '+(job.current_task||'first question'):''}`;
  $('liveRunNotice').textContent=[h.state==='unavailable'?h.timing_note:h.elapsed_s>=3600?'The one-hour score is frozen. Any later recorded answers remain in full-run diagnostics.':'Correct questions earn 1–2 points by difficulty within the first 60 active minutes. The run stops after 60 active minutes and plays a completion chime.',job.error,job.resume?.version_warning,job.state==='error'&&!job.resume?.allowed?job.resume?.reason:null].filter(Boolean).join(' ');
}
$('newRun').onclick=()=>{setPage('bench');selected=new Set(S.tasks.filter(t=>!t.issues.length).map(t=>t.id));$('search').value='';$('sectionFilter').value='';$('tierFilter').value='';updateSelection();$('runBuilder').scrollIntoView({behavior:'smooth',block:'center'});$('model').focus({preventScroll:true});toast(`${selected.size} questions selected. Choose a model and review your new run. Saved runs are retained.`)};
$('liveRunSelect').onchange=()=>{liveRunId=$('liveRunSelect').value;renderLiveRun()};
$('liveViewLog').onclick=()=>{logId=liveRunId;loadLog();$('logWrap').scrollIntoView({behavior:'smooth',block:'start'})};
$('liveResume').onclick=()=>reviewResume(liveRunId);
function reviewResume(id){
  const job=allJobs().find(j=>j.id===id);if(!job?.resume?.allowed)return;
  const p=job.resume;
  dialog('Resume '+job.model,`<p>Keep <strong>${p.preserved_attempts} completed attempts</strong> and retry or finish <strong>${p.remaining_attempts} attempts across ${p.remaining_questions} questions</strong>.</p><p>The saved question order and wrong-answer streak are retained. No timeouts. Previous logs and results remain available.</p>${p.version_warning?`<div class="notice">${esc(p.version_warning)}</div>`:''}`, [{label:'Back',click:()=>$('dialog').close()},{label:'Resume run',primary:true,click:async b=>{b.disabled=true;try{const r=await api('/api/resume',{job:id});liveRunId=r.job;logId=r.job;$('dialog').close();await refresh();toast('Run queued to resume.')}catch(e){toast(e.message);b.disabled=false}}}]);
}

$('liveClear').onclick=()=>reviewClearRun(liveRunId);
function reviewClearRun(id){
  const job=allJobs().find(j=>j.id===id);if(!job||['running','pending'].includes(job.state))return;
  dialog('Clear '+job.model+' run?',`<p>This removes this run from history and results, including any calibration reference assigned to it. A backup preserves its results, log and artifacts.</p><p>Your model settings and other runs stay in place. No new run starts automatically.</p>`,[{label:'Keep run',click:()=>$('dialog').close()},{label:'Clear run',primary:true,click:async b=>{b.disabled=true;try{const r=await api('/api/clear-run',{job:id});if(logId===id){logId=null;$('logWrap').classList.add('hidden')}if(liveRunId===id)liveRunId=null;calibrationData=null;$('dialog').close();await refresh();toast(`Run cleared. Backup: ${r.backup}`)}catch(e){toast(e.message);b.disabled=false}}}]);
}

$('liveStop').onclick=()=>stopRun(liveRunId);
async function stopRun(id){try{await api('/api/stop',{job:id});await refresh();toast('Stop requested. Completed results are retained.')}catch(e){toast(e.message)}}

function settingsHistory(records){
  return records.length?records.map(r=>`<div class="notice"><strong>User-reported · ${esc(new Date(r.recorded_at*1000).toLocaleString())}</strong><p>${r.applies_from==='run_start'?'Reported as applying from run start':'Settings changed'} · effective ${esc(new Date(r.effective_at*1000).toLocaleString())}</p><p>${Object.entries(r.settings).map(([k,v])=>`${esc(k)}: <strong>${esc(v)}</strong>`).join(' · ')}</p>${r.note?`<p>${esc(r.note)}</p>`:''}</div>`).join(''):'<p class="help">No user-reported settings. Blank fields remain unknown.</p>';
}
$('liveSettings').onclick=()=>editRunSettings(liveRunId);
function editRunSettings(id){
  const job=allJobs().find(j=>j.id===id);if(!job)return;
  const fields=['temperature','top_p','top_k','min_p','repetition_penalty'];
  dialog('Record server settings',`<p>Optional notes for <strong>${esc(job.model)}</strong>. Recording settings does not change them or interrupt the run.</p><p class="help">These values are user-reported. A chat preset may differ from API defaults; server-reported values stay separate.</p><div class="settings-fields">${fields.map(k=>`<label class="fieldlabel" for="reported-${k}">${esc(k.replaceAll('_',' '))}<input id="reported-${k}" type="number" min="0" ${['top_p','min_p'].includes(k)?'max="1"':''} step="${k==='top_k'?'1':'any'}" placeholder="Unknown"></label>`).join('')}<label class="fieldlabel" for="reported-reasoning">Reasoning settings<input id="reported-reasoning" maxlength="200" placeholder="For example: on, high, or server default"></label></div><label class="fieldlabel" for="reported-applies">When did these settings apply?</label><select id="reported-applies"><option value="">Choose timing…</option><option value="run_start" ${job.started?'':'disabled'}>In effect from the start of this run</option><option value="now" ${job.state==='running'?'':'disabled'}>Changed during the run — effective now</option></select><label class="fieldlabel" for="reported-note">Where did you read these settings? (optional)</label><textarea id="reported-note" maxlength="1000" rows="2" placeholder="For example: server API configuration, or LM Studio preset"></textarea><p id="reported-error" class="help" role="alert"></p><h3>Recorded history</h3>${settingsHistory(job.user_settings||[])}`,[{label:'Close',click:()=>$('dialog').close()},{label:'Save record',primary:true,click:async b=>{
    const settings={};for(const key of fields){const raw=$('reported-'+key).value;if(raw.trim())settings[key]=Number(raw)}
    const reasoning=$('reported-reasoning').value.trim();if(reasoning)settings.reasoning=reasoning;
    b.disabled=true;try{await api('/api/run-settings',{job:id,settings,applies_from:$('reported-applies').value,note:$('reported-note').value});$('dialog').close();await refresh();toast('User-reported settings saved. Previous records retained.')}catch(e){$('reported-error').textContent=e.message;b.disabled=false}
  }}]);
}


$('speedLane').onchange=()=>renderLiveRun();
function renderSpeed(job){
  const data=compareRunSpeed(S.results,job,$('speedLane').value,S.tasks),c=data.current;
  let html=c?`<p>Current: <strong>${seconds(c.seconds_per_attempt)} / attempt</strong> · ${c.attempts} completed · ${(c.accuracy*100).toFixed(1)}% correct · ${c.output_tokens_per_second.toFixed(1)} output tokens / wall second</p>`:'';
  if(!data.comparisons.length){$('liveSpeed').innerHTML=html+`<p class="help">${esc(data.reason)}</p>`;return}
  const max=Math.max(c.seconds_per_attempt,...data.comparisons.map(x=>x.seconds_per_attempt));
  html+=`<div class="speed-bar-row"><span>Current model</span><div class="speed-track"><div class="speed-bar current" style="width:${100*c.seconds_per_attempt/max}%"></div></div><strong>${seconds(c.seconds_per_attempt)}</strong></div>`;
  for(const r of data.comparisons){const ratio=r.current_speed_ratio;html+=`<div class="speed-bar-row"><span>${esc(r.model)}<small>${(r.accuracy*100).toFixed(1)}% correct · ${esc(new Date(r.ended*1000).toLocaleDateString())}</small></span><div class="speed-track"><div class="speed-bar" style="width:${100*r.seconds_per_attempt/max}%"></div></div><strong>${seconds(r.seconds_per_attempt)}</strong></div><p class="speed-ratio">Current model is <strong>${ratio.toFixed(2)}× as fast</strong> as ${esc(r.model)} on these ${c.attempts} attempts.</p>`}
  $('liveSpeed').innerHTML=html+'<p class="help">Bars show time per attempt; shorter is faster. Uses the latest matching run for each model.</p>';
}


function thinkingDetails(r){
  const t=r.thinking_settings||{},reportedDefault=t.server_reasoning_default??r.server_settings?.model?.capabilities?.reasoning?.default;
  const requests=r.requested_settings;
  const overrides=requests?.map(x=>Object.fromEntries(Object.entries(x.values||{}).filter(([k])=>['reasoning','reasoning_effort'].includes(k))));
  const sent=overrides?.length?[...new Set(overrides.map(x=>Object.keys(x).length?JSON.stringify(x):'No override — server default'))].join('; '):'Not captured';
  return `<dt>Pi thinking level</dt><dd>${esc(t.pi_thinking_level??'Not captured for this attempt')}<small>Pi’s internal setting; does not establish the server’s reasoning level.</small></dd><dt>Reasoning sent</dt><dd>${esc(sent)}</dd><dt>Server reasoning default</dt><dd>${esc(reportedDefault??'Not reported')}<small>Advertised default; effective reasoning level is not reported.</small></dd><dt>Thinking content observed</dt><dd>${t.thinking_content_observed===true?'Yes':t.thinking_content_observed===false?'No thinking content received':'Not captured'}</dd>`;
}


function questionReviewFlag(id){
  const flag=QUESTION_REVIEW_FLAGS[id];if(!flag)return '';
  const label=flag.status==='setup_candidate'?'Setup-check candidate':'Cut candidate';
  return ` <span class="question-review-flag">${label} <button type="button" class="metric-help" aria-label="Why ${esc(id)} is flagged" data-help="${esc(flag.reason+' Provisional review flag only. This question remains selected and scored normally. Compare the 27B, 9B and 0.8B results before deciding.')}" >?</button></span>`;
}


async function renderCurrentQuestion(){
  const job=S?.jobs.running[0],tid=job?.current_task;
  if(!tid){currentQuestionKey='';currentQuestionRequest++;$('currentQuestionStatus').textContent=job?'Waiting for the first question…':'No question is running right now.';$('currentQuestionContent').classList.add('hidden');return}
  const key=job.id+':'+tid;if(key===currentQuestionKey)return;
  currentQuestionKey=key;const request=++currentQuestionRequest;
  $('currentQuestionStatus').textContent=`${job.model} · ${tid} · Loading question…`;$('currentQuestionContent').classList.add('hidden');
  try{
    const [t,display]=await Promise.all([api('/api/task?id='+encodeURIComponent(tid)),api('/question-assets/'+encodeURIComponent(tid)+'/display.json')]);
    if(request!==currentQuestionRequest||S?.jobs.running[0]?.current_task!==tid||S?.jobs.running[0]?.id!==job.id)return;
    $('currentQuestionStatus').textContent=`${job.model} · ${tid} · In progress`;
    $('currentQuestionTitle').textContent=t.title||tid;$('currentQuestionPrompt').textContent=t.prompt;
    $('currentQuestionImages').innerHTML=(display.images||[]).map(url=>`<img src="${esc(url)}" alt="Chart supplied with ${esc(tid)}" loading="lazy">`).join('');
    const options=display.options||t.options.map(o=>typeof o==='string'?o:`${o.id} — ${o.text}`);
    $('currentOptionsHeading').textContent=options.length?`Answer options (${options.length})`:'Answer format';
    $('currentQuestionOptions').innerHTML=options.length?options.map(o=>`<li>${esc(o)}</li>`).join(''):'<li>This question uses a numeric answer or a tool submission; follow the prompt above.</li>';
    $('currentQuestionFiles').textContent=t.files.length?'Workspace files: '+t.files.join(', '):'';$('currentQuestionContent').classList.remove('hidden');
  }catch(e){if(request!==currentQuestionRequest)return;currentQuestionKey='';$('currentQuestionStatus').textContent='Could not load the current question: '+e.message}
}
