'use strict';
async function openRunEditor(id){
  let data;try{data=await api('/api/run-editor?job='+encodeURIComponent(id))}catch(e){toast(e.message);return}
  const current=data.history.at(-1),values=data.values||current?.values||{},job=allJobs().find(j=>j.id===id);
  let overridden=!!data.identity.overridden,generated=data.identity.generated_name||data.identity.name;
  const identity=['hardware','server_name','server_version','model_name','quantization'];
  const input=k=>`<label class="fieldlabel" for="detail-${k}">${esc(data.fields[k])}<input id="detail-${k}" list="choices-${k}" ${data.numeric.includes(k)?`type="number" step="${data.integer.includes(k)?'1':'any'}"`:'maxlength="2000"'} value="${esc(values[k]??data.identity.fields[k]??'')}"><datalist id="choices-${k}">${data.choices.filter(c=>c.field===k).map(c=>`<option value="${esc(c.value)}"></option>`).join('')}</datalist></label>`;
  const other=Object.keys(data.fields).filter(k=>k!=='run_name'&&!identity.includes(k));
  dialog('Configuration name',`<label class="fieldlabel" for="detail-run_name">Name<input id="detail-run_name" maxlength="500" value="${esc(data.identity.name)}"></label><button type="button" class="textbutton" id="detail-reset">Reset to generated name</button><p class="help">Names apply to every run of this configuration. Edit the server recipe to include details such as BF16KV or C1.</p><div class="settings-fields">${identity.map(input).join('')}</div><details><summary>Other run details</summary><div class="settings-fields">${other.map(input).join('')}</div></details><label class="fieldlabel" for="detail-timing">Details apply<select id="detail-timing"><option value="run_start">From run start / correction</option>${job?.state==='running'?'<option value="now">Changed during this run</option>':''}</select></label><label class="fieldlabel" for="detail-reason">Change note<input id="detail-reason" maxlength="2000"></label><p id="detail-error" role="alert"></p><details><summary>Captured execution record</summary><pre class="run-editor-captured">${esc(JSON.stringify({...data.captured,requested_settings:data.requested},null,2))}</pre></details><details><summary>Revision history (${data.history.length})</summary>${data.history.slice().reverse().map((r,i)=>`<p>${esc(new Date(r.recorded_at*1000).toLocaleString())} · ${esc(r.reason||'Saved details')} <button type="button" class="textbutton" data-restore-details="${i}">Restore</button></p>`).join('')}</details>`,[{label:'Cancel',click:()=>$('dialog').close()},{label:'Save',primary:true,click:async b=>{const next={};for(const k of Object.keys(data.fields)){const v=$('detail-'+k).value.trim();if(k==='run_name'&&!overridden)continue;if(v)next[k]=data.numeric.includes(k)?Number(v):v}b.disabled=true;try{await api('/api/run-editor',{job:id,values:next,base_revision:current?.id??null,applies_from:$('detail-timing').value,reason:$('detail-reason').value});$('dialog').close();await refresh();toast('Configuration name and details saved.')}catch(e){$('detail-error').textContent=e.message;b.disabled=false}}}]);
  let previewTimer,previewSequence=0;
  const previewName=()=>{clearTimeout(previewTimer);const sequence=++previewSequence;previewTimer=setTimeout(async()=>{const next={};for(const k of identity)next[k]=$('detail-'+k).value;try{const result=await api('/api/run-name',{job:id,values:next});if(sequence===previewSequence&&$('dialog').open){generated=result.generated_name||result.name;if(!overridden)$('detail-run_name').value=generated;$('detail-error').textContent='';}}catch(e){if(sequence===previewSequence&&$('dialog').open)$('detail-error').textContent=e.message;}},180);};
  for(const k of identity)$('detail-'+k).oninput=previewName;
  $('detail-run_name').oninput=()=>{overridden=true;};
  $('detail-reset').onclick=()=>{overridden=false;$('detail-run_name').value=generated;previewName();};
  $('dialog').classList.add('run-editor-dialog');
  $('dialog').addEventListener('close',()=>{clearTimeout(previewTimer);previewSequence++;$('dialog').classList.remove('run-editor-dialog');},{once:true});
  $('dialog').querySelectorAll('[data-restore-details]').forEach(b=>b.onclick=()=>{const old=data.history.slice().reverse()[Number(b.dataset.restoreDetails)].values;for(const k of Object.keys(data.fields))$('detail-'+k).value=old[k]??'';overridden=!!old.run_name;$('detail-reason').value='Restored an earlier revision';previewName();});
}
