'use strict';
async function openRunEditor(id){
  let data;try{data=await api('/api/run-editor?job='+encodeURIComponent(id))}catch(e){toast(e.message);return}
  const current=data.history.at(-1),values=current?.values||{},job=allJobs().find(j=>j.id===id);
  const groups=[['Identity',['run_name','model_name','model_revision','quantization']],['Server & hardware',['server_name','server_version','hardware','cache']],['Generation settings',['temperature','top_p','top_k','min_p','repetition_penalty','seed','context_limit','output_limit','reasoning','concurrency']],['Notes',['notes']]];
  const input=k=>`<label class="fieldlabel" for="detail-${k}">${esc(data.fields[k])}<input id="detail-${k}" list="choices-${k}" ${data.numeric.includes(k)?`type="number" step="${data.integer.includes(k)?'1':'any'}"`:'maxlength="2000"'} value="${esc(values[k]??'')}" placeholder="${k==='model_name'?esc(job.model):'Choose saved or type new…'}"><datalist id="choices-${k}">${data.choices.filter(c=>c.field===k).map(c=>`<option value="${esc(c.value)}"></option>`).join('')}</datalist></label>`;
  dialog('Run editor',`<p>Your editor setup is saved for this configuration and hardware, including all fields below. New runs reuse it automatically, even after results are deleted. Review inherited details if your server settings changed.</p><div class="run-editor-badge">User-reported details · revision ${data.history.length||'new'}</div>${groups.map(([title,keys])=>`<fieldset class="run-editor-group"><legend>${title}</legend><div class="settings-fields">${keys.map(input).join('')}</div></fieldset>`).join('')}<label class="fieldlabel" for="detail-timing">When did these details apply?</label><select id="detail-timing"><option value="run_start">From run start / correction to recorded details</option>${job.state==='running'?'<option value="now">Changed during this run — effective now</option>':''}</select><label class="fieldlabel" for="detail-reason">Change note<input id="detail-reason" maxlength="2000" placeholder="Optional source or reason for this revision"></label><p class="help">These are descriptive records. Model, quantization, server, hardware and generation labels also populate score preview; notes stay local. Actual execution settings and original results stay visible below. Blank means unknown.</p><p id="detail-error" role="alert"></p><details><summary>Captured execution record</summary><pre class="run-editor-captured">${esc(JSON.stringify({...data.captured,requested_settings:data.requested},null,2))}</pre></details><details><summary>Revision history (${data.history.length})</summary>${data.history.slice().reverse().map((r,i)=>`<article class="notice"><strong>${esc(new Date(r.recorded_at*1000).toLocaleString())}</strong><p>${esc(r.reason||'Saved run details')} · ${r.applies_from==='now'?'changed during run':'from run start'}</p><p>${Object.entries(r.values).map(([k,v])=>esc(data.fields[k])+': '+esc(v)).join(' · ')}</p><button type="button" class="textbutton" data-restore-details="${i}">Use these values</button></article>`).join('')||'<p>No previous revisions.</p>'}</details>`,[{label:'Cancel',click:()=>$('dialog').close()},{label:'Save revision',primary:true,click:async b=>{const next={};for(const k of Object.keys(data.fields)){const v=$('detail-'+k).value.trim();if(v)next[k]=data.numeric.includes(k)?Number(v):v}b.disabled=true;try{await api('/api/run-editor',{job:id,values:next,base_revision:current?.id??null,applies_from:$('detail-timing').value,reason:$('detail-reason').value});$('dialog').close();await refresh();toast('Run details saved. New choices are available for future edits.')}catch(e){$('detail-error').textContent=e.message;b.disabled=false}}}]);
  $('dialog').classList.add('run-editor-dialog');
  $('dialog').addEventListener('close',()=>$('dialog').classList.remove('run-editor-dialog'),{once:true});
  $('dialog').querySelectorAll('[data-restore-details]').forEach(b=>b.onclick=()=>{const old=data.history.slice().reverse()[Number(b.dataset.restoreDetails)].values;for(const k of Object.keys(data.fields))$('detail-'+k).value=old[k]??'';$('detail-reason').value='Restored values from an earlier revision';});
}
